package pl.poznan.ilim.havok.entities;
// Generated 2011-02-04 09:10:43 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "items", catalog = "havok")
public class Item extends LightEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 8073931113030061169L;
	private String id;
	private String description;
	private Float price;
	private List<Observation> observations = new ArrayList<Observation>(0);

	public Item() {
	}

	public Item(String id) {
		this.id = id;
	}

	public Item(String id, String description, Float price, List<Observation> observations) {
		this.id = id;
		this.description = description;
		this.price = price;
		this.observations = observations;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getGtin() {
		return this.id;
	}

	public void setGtin(String id) {
		this.id = id;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@OneToMany(targetEntity=Observation.class, 
			fetch = FetchType.EAGER, mappedBy = "item")
	public List<Observation> getObservations() {
		return this.observations;
	}

	public void setObservations(List<Observation> observations) {
		this.observations = observations;
	}
}
