package pl.poznan.ilim.havok.entities;
// Generated 2011-02-04 09:10:43 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "statuses", catalog = "havok", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Status extends LightEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 428096748408349303L;
	private Integer id;
	private String name;
	private String colorCss;
	private List<Observation> observations = new ArrayList<Observation>(0);

	public Status() {
	}

	public Status(String name) {
		this.name = name;
	}

	public Status(String name, String colorCss, List<Observation> observations) {
		this.name = name;
		this.colorCss = colorCss;
		this.observations = observations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "color_css", length = 20)
	public String getColorCss() {
		return this.colorCss;
	}

	public void setColorCss(String colorCss) {
		this.colorCss = colorCss;
	}

	@OneToMany(targetEntity=Observation.class,
			fetch = FetchType.EAGER, mappedBy = "status")
	public List<Observation> getObservations() {
		return this.observations;
	}

	public void setObservations(List<Observation> observations) {
		this.observations = observations;
	}

}
